name: sola
description: im project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 常用工具类 https://pub.dev/packages/common_utils
  common_utils: ^2.1.0
  # 动画 https://pub.dev/packages/animations
  animations: ^2.0.7
  # 角标 https://pub.dev/packages/badges
  badges: ^2.0.3
  # 图片算法 https://pub.dev/packages/blurhash_dart
  blurhash_dart: ^1.1.0
  # 通话控制 https://pub.dev/packages/callkeep
  callkeep: ^0.3.2
  # 网络状态检测 https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^3.0.2
  # 设备信息 https://pub.dev/packages/device_info_plus
  device_info_plus: ^8.0.0
  # 屏幕适配 https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.6.0
  # 锁定屏幕 https://pub.dev/packages/flutter_app_lock
  flutter_app_lock: ^3.0.0
  # 应用通知 https://pub.dev/packages/flutter_app_badger
  flutter_app_badger: ^1.5.0
  # 本地通知 https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^12.0.4
  # 防止进入后台进程被杀死 https://pub.dev/packages/flutter_foreground_task
  flutter_foreground_task: ^3.10.0
  # 防止屏幕锁屏 https://pub.dev/packages/wakelock
  wakelock: ^0.6.2
  # url launch https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.7
  # dialog https://pub.dev/packages/adaptive_dialog
  adaptive_dialog: ^1.8.0+1
  # 主题色 切换 https://pub.dev/packages/adaptive_theme
  adaptive_theme: ^3.1.1
  # 国际化
  flutter_localizations:
    sdk: flutter
  # 国际化 https://pub.dev/packages/intl
  intl: ^0.17.0
  # 状态管理 https://pub.dev/packages/get
  get: ^4.6.5
  # 路径管理 https://pub.dev/packages/path_provider
  path_provider: ^2.0.11
  # 文件打开读写处理 https://pub.dev/packages/file_picker_cross
  file_picker_cross: ^4.6.0
  # 权限管理 https://pub.dev/packages/permission_handler
  permission_handler: ^10.2.0
  # 安全、去中心化通信的开放网络 https://pub.dev/packages/matrix , 官网https://matrix.org/
  matrix: ^0.15.6
  # warning flutter_webrtc: 0.9.14 # Pinned because >0.9.14 add Linux support which lets build fail
  # webrtc 实时通讯 语音视频 https://pub.dev/packages/flutter_webrtc
  flutter_webrtc: ^0.9.17
  # webrtc interface https://pub.dev/packages/webrtc_interface
  webrtc_interface: ^1.0.10
  # link_text 可点击样式 https://pub.dev/packages/matrix_link_text
  matrix_link_text: ^1.0.2
  # 二维码扫描 https://pub.dev/packages/qr_code_scanner
  qr_code_scanner: ^1.0.1
  # 二维码生成
  qr_flutter: ^4.0.0
  # 音视频压缩 https://pub.dev/packages/video_compress
  video_compress: ^3.1.2
  # 通知、小铃声播放 https://pub.dev/packages/flutter_ringtone_player
  flutter_ringtone_player: ^3.2.0
  # 播放器 https://pub.dev/packages/chewie
  chewie: ^1.3.6
  # 视频播放 https://pub.dev/packages/video_player
  video_player: ^2.4.8
  # 语音播放 https://pub.dev/packages/just_audio
  just_audio: ^0.9.30
  # 地理位置 https://pub.dev/packages/geolocator
  geolocator: ^9.0.2
  # 经纬度计算 https://pub.dev/packages/latlong2
  latlong2: ^0.8.1
  # 录音到文件 https://pub.dev/packages/record
  record: ^4.4.3
  # 震动 https://pub.dev/packages/vibration
  vibration: ^1.7.6
  # deep link https://pub.dev/packages/uni_links
  uni_links: ^0.5.1
  # 通知发送 https://pub.dev/packages/unifiedpush
  unifiedpush: ^4.0.3
  # 图片解析全类型 https://pub.dev/packages/universal_image
  universal_image: ^0.1.6
  # 大图变小占位图的显示 https://pub.dev/packages/flutter_blurhash hash LEHV6nWB2yk8pyo0adR*.7kCMdnj
  flutter_blurhash: ^0.7.0
  # 表情控件 https://pub.dev/packages/emoji_picker_flutter
  emoji_picker_flutter: ^1.5.1
  # 关键字表情提示 https://pub.dev/packages/emoji_proposal
  emoji_proposal: ^0.0.1
  # Unicode 13.1 Emojis https://pub.dev/packages/emojis
  emojis: ^0.9.9
  # 加密 https://pub.dev/packages/encrypt
  encrypt: ^5.0.1
  # 键盘快捷按键 https://pub.dev/packages/keyboard_shortcuts 
  keyboard_shortcuts: ^0.1.4
  # 网络框架 https://pub.dev/packages/dio
  dio: ^4.0.6
  # 日志打印 https://pub.dev/packages/logger
  logger: ^1.1.0
  # dev-闪屏 https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.2.15
  # ------ dev ------
  # debug-不同机器显示样式式 https://pub.dev/packages/device_preview
  device_preview: ^1.1.0
  # 表单
  reactive_forms: ^14.1.0
  # 状态管理
  provider: ^6.0.4
  # 图片
  extended_image: ^6.3.4
  # 虚线边框
  r_dotted_line_border: ^0.1.1
  # 获取图片资源
  photo_manager: ^2.5.2
  # 裁剪图片
  crop_image: ^1.0.3
dev_dependencies:

  # debug-代码分析工具 https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.17.1
  # debug-引入分组 https://pub.dev/packages/import_sorter
  import_sorter: ^4.6.0
  # dev-icon https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.11.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  #file_picker_cross, matrix 库不兼容
  ffi: ^2.0.1
  # collections https://pub.dev/packages/collection
  collection: ^1.17.0
  # 包信息 https://pub.dev/packages/package_info_plus
  package_info_plus: ^3.0.2

# 等待图片配置
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/splash.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/to/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/to/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/to/icon.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # assets-generator-begin
    # assets/icon/*
    - assets/icon/add_by_qrcode_icon.png
    - assets/icon/add_contacts_icon.png
    - assets/icon/add_grey_icon.png
    - assets/icon/add_icon.png
    - assets/icon/auto_delete_icon.png
    - assets/icon/camera_icon.png
    - assets/icon/change_password_icon.png
    - assets/icon/chat_add_more_icon.png
    - assets/icon/chat_contact_icon.png
    - assets/icon/chat_file_icon.png
    - assets/icon/chat_gallery_icon.png
    - assets/icon/chat_location_icon.png
    - assets/icon/chat_voicce_input_icon.png
    - assets/icon/chat_voice_call_icon.png
    - assets/icon/chats_select_icon.png
    - assets/icon/check_box_select_icon.png
    - assets/icon/check_box_unselect_icon.png
    - assets/icon/checkbox_input.png
    - assets/icon/checkbox_uninput.png
    - assets/icon/close_eye_icon.png
    - assets/icon/collection_icon.png
    - assets/icon/communication_blue_icon.png
    - assets/icon/communication_icon.png
    - assets/icon/contacts_unselect_icon.png
    - assets/icon/copy_icon.png
    - assets/icon/create_group_icon.png
    - assets/icon/crop_icon.png
    - assets/icon/delete_blue_icon.png
    - assets/icon/delete_chat_icon.png
    - assets/icon/delete_icon.png
    - assets/icon/done_icon.png
    - assets/icon/download_icon.png
    - assets/icon/edit_icon.png
    - assets/icon/email_icon.png
    - assets/icon/emoji_icon.png
    - assets/icon/empty_place_hold.png
    - assets/icon/exit_org_icon.png
    - assets/icon/eye_icon.png
    - assets/icon/flip_icon.png
    - assets/icon/flip_icon_2.png
    - assets/icon/forward_icon.png
    - assets/icon/forward_icon_2.png
    - assets/icon/grey_close_icon.png
    - assets/icon/group_notification.png
    - assets/icon/hand_up_icon.png
    - assets/icon/icon.png
    - assets/icon/info_icon.png
    - assets/icon/language_icon.png
    - assets/icon/like_icon.png
    - assets/icon/list_more_icon.png
    - assets/icon/log_out_icon.png
    - assets/icon/logo_icon.png
    - assets/icon/make_as_read_icon.png
    - assets/icon/more_icon.png
    - assets/icon/mute_icon.png
    - assets/icon/my_org_icon.png
    - assets/icon/notifaction_icon.png
    - assets/icon/org_info_icon.png
    - assets/icon/org_name_icon.png
    - assets/icon/org_notification.png
    - assets/icon/password_icon.png
    - assets/icon/pin_icon.png
    - assets/icon/profile_unselect_icon.png
    - assets/icon/radio_select_icon.png
    - assets/icon/radio_unselect_icon.png
    - assets/icon/remove_icon.png
    - assets/icon/reply_icon.png
    - assets/icon/right_black_icon.png
    - assets/icon/right_icon.png
    - assets/icon/rotate_icon.png
    - assets/icon/s_blue_icon.png
    - assets/icon/s_icon.png
    - assets/icon/scan_qrcode_icon.png
    - assets/icon/search_icon.png
    - assets/icon/security_icon.png
    - assets/icon/select_icon.png
    - assets/icon/select_swich.png
    - assets/icon/sola_blue_icon.png
    - assets/icon/sola_icon.png
    - assets/icon/splash_icon1.png
    - assets/icon/splash_icon2.png
    - assets/icon/splash_icon3.png
    - assets/icon/success_blue_icon.png
    - assets/icon/success_white_icon.png
    - assets/icon/time_icon.png
    - assets/icon/unselect_icon.png
    - assets/icon/username_icon.png
    - assets/icon/version_icon.png
    - assets/icon/voice_clip_icon.png
    - assets/icon/voice_icon.png
    - assets/icon/voice_icon_2.png
    - assets/icon/warning_icon.png
    # assets/to/*
    - assets/to/icon.png
    # assets-generator-end

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
